### ISSUE TITLE
Document the magic numbers in retirement_api/utils

### ISSUE THREAD

**Issue by willbarton** [cfpb/retirement#105]
There are several numbers [in the `ss_calculator.py` file](https://github.com/cfpb/retirement/blob/master/retirement_api/utils/ss_calculator.py#L89) that are undocumented, and it's unclear what their meaning is. Can we document them, so that someone coming to the project in the future can understand what's going on here?

**Comment by higs4281** [comment]
addressed in [PR 108](https://github.com/cfpb/retirement/pull/108)

**Comment by willbarton** [comment]
Excellente :+1:
