### ISSUE TITLE
IE8 breakage

### ISSUE THREAD

**Issue by Scotchester** [cfpb/retirement#107]
The tool is non-functional in IE8. After clicking "Get your estimates", here's what I see:

![screen shot 2015-08-28 at 16 40 14](https://cloud.githubusercontent.com/assets/1044670/9556558/9b10b206-4da3-11e5-9c4e-e49663e47b2b.png)
![screen shot 2015-08-28 at 16 41 04](https://cloud.githubusercontent.com/assets/1044670/9556561/9faf405c-4da3-11e5-9868-3fa37dc64177.png)

Here are the reported JS errors:

---

Message: Invalid argument.
Line: 11
Char: 24781
Code: 0
URI: http://www.consumerfinance.gov/static/retirement/js/raphael-min.js

Message: Object doesn't support this property or method
Line: 489
Char: 5
Code: 0
URI: http://www.consumerfinance.gov/static/retirement/js/claiming-social-security.js

Message: Script error
Line: 0
Char: 0
Code: 0
URI: http://www.googletagmanager.com/gtm.js?id=GTM-KMMLRS

Message: Script error
Line: 0
Char: 0
Code: 0
URI: http://www.googletagmanager.com/gtm.js?id=GTM-KMMLRS

Message: Script error
Line: 0
Char: 0
Code: 0
URI: http://www.googletagmanager.com/gtm.js?id=GTM-KMMLRS

Message: Script error
Line: 0
Char: 0
Code: 0
URI: http://www.googletagmanager.com/gtm.js?id=GTM-KMMLRS

Message: Failed
Line: 11
Char: 20441
Code: 0
URI: http://www.consumerfinance.gov/static/retirement/js/raphael-min.js

Message: Failed
Line: 11
Char: 20441
Code: 0
URI: http://www.consumerfinance.gov/static/retirement/js/raphael-min.js

Message: Script error
Line: 0
Char: 0
Code: 0
URI: http://www.googletagmanager.com/gtm.js?id=GTM-KMMLRS

**Comment by mistergone** [comment]
After a quick look, the problem looks to be coming from the Raphael setSize() method called in setGraphDimensions. I'm think it's being passed a 0 an equally invalid argument in some way, so that's where I'll start the debugging.

**Comment by anselmbradford** [comment]
Do we care about this issue any more?

**Comment by Scotchester** [comment]
Seeing as we don't serve application JS to IE8 anymore, no.
