### ISSUE TITLE
Spanish page title appears as half English and half Spanish

### ISSUE THREAD

**Issue by OrlandoSoto** [cfpb/retirement#118]
Spanish page title shows up as half English and half Spanish
http://www.consumerfinance.gov/retirement/before-you-claim/es/

it appears as "Before You Claim | Oficina para la Protección Financiera del Consumidor"

the "Before You Claim" portion should probably also be translated to Español

**Comment by OrlandoSoto** [comment]
cc: @SerenaEstrella

**Comment by marteki** [comment]
Ooo, great catch. Thanks, Orlando!

**Comment by higs4281** [comment]
addressed in PR 119
