### ISSUE TITLE
Extra .cf-icon code shrinks the footer buttons in the new footer

### ISSUE THREAD

**Issue by KimberlyMunoz** [cfpb/retirement#161]
Hey FPO,

There's a small issue in the footer, where extra code for `.cf-icon` shrinks all the icons we have the footer. Ideally those styles should be coming in from Capital Framework and any non-standard sizing should be handled through another class to not conflict with other `.cf-icon`s. [Deleting this line](https://github.com/cfpb/retirement/blame/master/src/css/claiming.less#L1110) should fix the issue, but L1103-1111 could be removed to have Capital Framework handle any future changes. 

## Current behavior
![image](https://cloud.githubusercontent.com/assets/1860176/14509318/a6fb972a-0199-11e6-8b24-17debdeac587.png)

Viewable at http://beta.consumerfinance.gov/retirement/before-you-claim/

## Expected behavior

![image](https://cloud.githubusercontent.com/assets/1860176/14509368/e3b85df6-0199-11e6-80ad-cfdfbc1e9d4c.png)

## Can you fix it?
@niqjohnson @mistergone :pray:

**Comment by marteki** [comment]
Fixed in PR https://github.com/cfpb/retirement/pull/162
