### ISSUE TITLE
Invalid dates aren't properly handled

### ISSUE THREAD

**Issue by chosak** [cfpb/retirement#194]
Entering an invalid date such as February 29, 1952 returns a 500 error from the API:

http://www.consumerfinance.gov/retirement/retirement-api/estimator/2-29-1952/10000/

The frontend just spins indefinitely with no indication that the input was invalid:

![image](https://cloud.githubusercontent.com/assets/654645/22661298/e576a1b0-ec72-11e6-9401-938ce6128ea0.png)

Expected behavior is that the API should return a 400 Bad Request (to be consistent with handling of other invalid inputs) and that some kind of error should be reflected in the UI.

**Comment by higs4281** [comment]
Ha! 2/29/1952 actually is a valid leap-year date, but there was some old code that failed to find a birthday in the current year.

The tool has client-side date-checking, so if you enter a truly invalid date (2/30/1952), it will dial back the date to a valid entry (2/29), but then *that* was bombing.

Addressed in PR #195

**Comment by chosak** [comment]
> 2/29/1952 actually is a valid leap-year date

Agh, leap years, how do they work?! Thanks for submitting the PR so quickly, I will review.

**Comment by chosak** [comment]
Fixed in #195, thanks @higs4281!
