### ISSUE TITLE
Security Findings

### ISSUE THREAD

**Issue by lfatty** [cfpb/retirement#52]
Hello Team,
I have reviewed the source codes and found few security issues that I would like to discuss with anyone available.

**Comment by higs4281** [comment]
discussed and fixed

**Comment by higs4281** [comment]
For security testing: the form fields are checked to make sure they are numeric; any non-numeric string values are discarded and replaced with default numbers 1, 0 ,or 1900, depending on the field.
if a string gets past the javascript check somehow, the calculator also checks values and returns an error if a date or salary value is not an integer. the calculator checks are tested [here](https://github.com/cfpb/retirement/blob/master/retirement_api/utils/tests/test_ss_utilities.py)
