### ISSUE TITLE
Error message overlaps text when zoom is greater than 100%

### ISSUE THREAD

**Issue by OrlandoSoto** [cfpb/retirement#69]
This only happens when I set my browser zoom higher than 100%.
The attached screenshot is with 110% browser zoom on Chrome
![retirementoverlap](https://cloud.githubusercontent.com/assets/7442823/8828577/f03e2b92-3060-11e5-9e1f-a43a1a6b9384.png)

**Comment by higs4281** [comment]
fixed. thanks, @OrlandoSoto !
